<style>
    span.phing_err {
        color: #ba2828;
    }
    span.phing_verbose {
        color: #8c3265;
    }
    span.phing_debug {
        color: #6c6c6c;
    }
    span.phing_warn {
        color: #8c5633;
    }
    span.phing_info {
        color: #8c8b32;
    }
/*    const CLASS_ERR     = '';
    const CLASS_VERBOSE = 'phing_verbose';
    const CLASS_DEBUG   = 'phing_debug';
    const CLASS_WARN    = 'phing_warn';
    const CLASS_INFO    = 'phing_info';*/

</style>

<strong>command </strong>
<pre><?php echo $this->command; ?></pre>
<strong>returnStatus</strong>
<pre><?php echo $this->returnStatus; ?></pre>
<strong>output </strong>
<pre><?php echo $this->output; ?></pre>